slurm:
  shared_scratch: /cluster/sesonas13/$SLURM_JOB_USER/$SLURM_JOB_ID
  partitions:
    - partition1
  default_partition: 'partition1'

abaqus:
  # default template
  solve_template: 'abaqus-solve-template.j2'
  solve_parallel_template: 'abaqus-solve-parallel-template.j2'
  # Populated modules list
  envmodules:
    - 'abaqus/2018-2'
    - 'abaqus/2019-G'

femfat:
  template: 'femfat_slurm.j2'
  envmodules:
    - 'femfat/1'

tensorflow:
  template: 'tensor-demo.j2'
