slurm:
  shared_scratch: /cluster/sesonas13/$SLURM_JOB_USER/$SLURM_JOB_ID
  partitions:
    - partition1
  default_partition: 'partition1'

abaqus:
  # default template
  solve_template: 'abaqus-solve-template.j2'
  solve_distributed_template: 'abaqus-solve-distributed-template.j2'
  solve_eigenfrequency_template: 'abaqus-solve-eigenfreqency-template.j2'
  # Populated modules list
  envmodules:
    - 'abaqus/2018-2'
    - 'abaqus/2019-G'
  masternode_mem:
    - '384'
    - '768'
    - '1536'
  masternode_mem_default:
    - '768'
  workernode_mem_default:
    - '384'

femfat:
  template: 'femfat_slurm.j2'
  envmodules:
    - 'femfat/1'

tensorflow:
  template: 'tensor-demo.j2'
